# Generated by Django 3.2.14 on 2022-07-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
    ]
